"""empty message

Revision ID: 4e51aa5899de
Revises: None
Create Date: 2017-03-06 10:38:02.615531

"""

# revision identifiers, used by Alembic.
revision = '4e51aa5899de'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_name', sa.String(), nullable=True),
    sa.Column('oauth_token', sa.String(), nullable=True),
    sa.Column('oauth_token_secret', sa.String(), nullable=True),
    sa.Column('csv_data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
